services:
  web:
    build: .
    command: python marketing_site/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app
      - DEBUG=True
      - DJANGO_DB_NAME=your_db_name
      - DJANGO_DB_USER=your_db_user
      - DJANGO_DB_PASSWORD=your_db_password
      - DJANGO_DB_HOST=db  # Указывает на сервис базы данных
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: marketing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge